//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAGRILAR_TBL
    {
        public long CAG_ID { get; set; }
        public Nullable<long> CAG_CAL_ID { get; set; }
        public Nullable<long> CAG_KUL_ID { get; set; }
        public Nullable<System.DateTime> CAG_TARIH { get; set; }
        public string CAG_TELNO { get; set; }
        public string CAG_ACIKLAMA { get; set; }
        public Nullable<long> CAG_CK_ID { get; set; }
        public string CAG_SANTRALCIKISKODU { get; set; }
        public Nullable<long> CAG_IST_ID { get; set; }
        public Nullable<System.TimeSpan> CAG_SURE { get; set; }
        public Nullable<System.DateTime> CAG_BASLAMA { get; set; }
        public Nullable<System.DateTime> CAG_BITIS { get; set; }
        public Nullable<long> CAG_RAN_ID { get; set; }
    
        public virtual ISTEKLER_TBL ISTEKLER_TBL { get; set; }
    }
}
