//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALISMALAR_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CALISMALAR_TBL()
        {
            this.CALISMACIKISKODLARI_TBL = new HashSet<CALISMACIKISKODLARI_TBL>();
            this.CALISMAPERIYOTLARI_TBL = new HashSet<CALISMAPERIYOTLARI_TBL>();
            this.CALISMATAKVIMI_TBL = new HashSet<CALISMATAKVIMI_TBL>();
            this.KULLANICICALISMALAR_TBL = new HashSet<KULLANICICALISMALAR_TBL>();
            this.RANDEVULAR_TBL = new HashSet<RANDEVULAR_TBL>();
        }
    
        public long CAL_ID { get; set; }
        public string CAL_ADI { get; set; }
        public string CAL_PERIYOT { get; set; }
        public Nullable<System.DateTime> CAL_BASLAMATARIH { get; set; }
        public Nullable<System.DateTime> CAL_BITISTARIH { get; set; }
        public Nullable<System.TimeSpan> CAL_GUNBASLAMASAAT { get; set; }
        public Nullable<System.TimeSpan> CAL_GUNBITISSAAT { get; set; }
        public Nullable<System.TimeSpan> CAL_RANDEVUARALIK { get; set; }
        public Nullable<bool> CAL_MANUELARAMA { get; set; }
        public string CAL_CALISMAID { get; set; }
        public Nullable<System.DateTime> CAL_YIL { get; set; }
        public Nullable<bool> CAL_SEC { get; set; }
        public Nullable<bool> CAL_SIL { get; set; }
        public Nullable<System.DateTime> CAL_SILME_TARIH { get; set; }
        public Nullable<int> CAL_SILME_KUL_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALISMACIKISKODLARI_TBL> CALISMACIKISKODLARI_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALISMAPERIYOTLARI_TBL> CALISMAPERIYOTLARI_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALISMATAKVIMI_TBL> CALISMATAKVIMI_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KULLANICICALISMALAR_TBL> KULLANICICALISMALAR_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RANDEVULAR_TBL> RANDEVULAR_TBL { get; set; }
    }
}
