//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALISMAPERIYOTLARI_TBL
    {
        public Nullable<long> CP_CAL_ID { get; set; }
        public Nullable<int> CP_REFDONEM { get; set; }
        public Nullable<int> CP_REFAY { get; set; }
        public Nullable<int> CP_REFHAFTA { get; set; }
        public Nullable<System.DateTime> CP_REF_MA_BASLANGIC { get; set; }
        public Nullable<System.DateTime> CP_REF_MA_BITIS { get; set; }
        public Nullable<bool> CP_AKTIF { get; set; }
        public Nullable<System.DateTime> CP_BASLAMATARIH { get; set; }
        public Nullable<System.DateTime> CP_BITISTARIH { get; set; }
        public Nullable<System.DateTime> CP_REFYIL { get; set; }
        public long CP_ID { get; set; }
    
        public virtual CALISMALAR_TBL CALISMALAR_TBL { get; set; }
    }
}
