//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALISMATAKVIMI_TBL
    {
        public long CT_ID { get; set; }
        public Nullable<long> CT_CAL_ID { get; set; }
        public string CT_ADI { get; set; }
        public Nullable<System.DateTime> CT_BASLAMA { get; set; }
        public Nullable<System.DateTime> CT_BITIS { get; set; }
        public Nullable<bool> CT_CALIS { get; set; }
        public Nullable<bool> CT_SIL { get; set; }
        public Nullable<System.DateTime> CT_SILME_TARIH { get; set; }
        public Nullable<int> CT_SILME_KUL_ID { get; set; }
    
        public virtual CALISMALAR_TBL CALISMALAR_TBL { get; set; }
    }
}
