//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIKISKODLARI_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CIKISKODLARI_TBL()
        {
            this.CALISMACIKISKODLARI_TBL = new HashSet<CALISMACIKISKODLARI_TBL>();
        }
    
        public long CK_ID { get; set; }
        public string CK_KOD { get; set; }
        public string CK_ACIKLAMA { get; set; }
        public Nullable<bool> CK_SEC { get; set; }
        public Nullable<bool> CK_AKTIF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALISMACIKISKODLARI_TBL> CALISMACIKISKODLARI_TBL { get; set; }
    }
}
