//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORUMKONULARI_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORUMKONULARI_TBL()
        {
            this.MESAJLAR_TBL = new HashSet<MESAJLAR_TBL>();
        }
    
        public long FR_ID { get; set; }
        public Nullable<System.DateTime> FR_OLUSTURMATARIH { get; set; }
        public string FR_ADI { get; set; }
        public string FR_ACIKLAMA { get; set; }
        public Nullable<bool> FR_AKTIF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MESAJLAR_TBL> MESAJLAR_TBL { get; set; }
    }
}
