//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENELAYARLAR_TBL
    {
        public long GA_ID { get; set; }
        public Nullable<System.TimeSpan> GA_GUNBASLAMASAAT { get; set; }
        public Nullable<System.TimeSpan> GA_GUNBITISSAAT { get; set; }
        public Nullable<bool> GA_CUMARTESICALIS { get; set; }
        public Nullable<bool> GA_PAZARCALIS { get; set; }
        public string GA_ANASAYFA_BASLIK { get; set; }
        public string GA_FTP_IP { get; set; }
        public string GA_FTP_KULLANICI { get; set; }
        public string GA_FTP_SIFRE { get; set; }
        public string GA_FTP_DIZIN { get; set; }
        public string GA_RANDEVUISTEKSAYFA { get; set; }
        public Nullable<int> GA_ROLSIRA { get; set; }
        public string GA_CIHAZIP { get; set; }
        public Nullable<System.TimeSpan> GA_YAKLASANRANDEVUDK { get; set; }
        public string GA_VERSIYON { get; set; }
    }
}
