//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISTEKLER_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ISTEKLER_TBL()
        {
            this.CAGRILAR_TBL = new HashSet<CAGRILAR_TBL>();
            this.RANDEVULAR_TBL = new HashSet<RANDEVULAR_TBL>();
        }
    
        public long IST_ID { get; set; }
        public Nullable<System.DateTime> IST_TARIH { get; set; }
        public string IST_CALISMAID { get; set; }
        public string IST_KULLANICIID { get; set; }
        public Nullable<long> IST_BIRIMNO { get; set; }
        public Nullable<long> IST_ALTBIRIMNO { get; set; }
        public Nullable<int> IST_REFYIL { get; set; }
        public Nullable<int> IST_REFDONEM { get; set; }
        public Nullable<int> IST_REFAY { get; set; }
        public Nullable<int> IST_REFHAFTA { get; set; }
        public string IST_TELNO { get; set; }
        public string IST_IL { get; set; }
        public string IST_ACIKLAMA { get; set; }
        public string IST_RANDEVUTERCIH { get; set; }
        public string IST_NEDIR { get; set; }
        public Nullable<bool> IST_OKUNDU { get; set; }
        public Nullable<bool> IST_ICERDEN { get; set; }
        public Nullable<System.DateTime> IST_KAPANMAZAMANI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAGRILAR_TBL> CAGRILAR_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RANDEVULAR_TBL> RANDEVULAR_TBL { get; set; }
    }
}
