//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICICALISMALAR_TBL
    {
        public long KC_ID { get; set; }
        public Nullable<long> KC_KUL_ID { get; set; }
        public Nullable<long> KC_CAL_ID { get; set; }
    
        public virtual CALISMALAR_TBL CALISMALAR_TBL { get; set; }
        public virtual KULLANICILAR_TBL KULLANICILAR_TBL { get; set; }
    }
}
