//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_TBL
    {
        public long LG_ID { get; set; }
        public Nullable<System.DateTime> LG_TARIH { get; set; }
        public Nullable<long> LG_KUL_ID { get; set; }
        public string LG_ISLEM { get; set; }
        public string LG_ISLEMDETAY { get; set; }
    }
}
