//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESAJLAR_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MESAJLAR_TBL()
        {
            this.MESAJALICILARI_TBL = new HashSet<MESAJALICILARI_TBL>();
        }
    
        public long MSJ_ID { get; set; }
        public Nullable<long> MSJ_KUL_ID { get; set; }
        public Nullable<long> MSJ_FR_ID { get; set; }
        public Nullable<System.DateTime> MSJ_TARIH { get; set; }
        public string MSJ_MESAJ { get; set; }
        public Nullable<bool> MSJ_OKUNDU { get; set; }
    
        public virtual FORUMKONULARI_TBL FORUMKONULARI_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MESAJALICILARI_TBL> MESAJALICILARI_TBL { get; set; }
    }
}
