//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class mv_tuik_personel
    {
        public string tc_kimlik_no { get; set; }
        public string adsoyad { get; set; }
        public string dairebsk_adi { get; set; }
        public string birim_adi { get; set; }
        public string birim_kod { get; set; }
        public string kisadaire_bask_kod { get; set; }
    }
}
