//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANDEVULAR_TBL
    {
        public long RAN_ID { get; set; }
        public Nullable<long> RAN_CAL_ID { get; set; }
        public Nullable<long> RAN_KUL_ID { get; set; }
        public Nullable<System.DateTime> RAN_BASLAMATARIH { get; set; }
        public Nullable<System.DateTime> RAN_BITISTARIH { get; set; }
        public string RAN_TELNO { get; set; }
        public string RAN_ACIKLAMA { get; set; }
        public Nullable<long> RAN_DURUMID { get; set; }
        public Nullable<long> RAN_IST_ID { get; set; }
        public Nullable<bool> RAN_SEC { get; set; }
        public Nullable<System.DateTime> RAN_ACMA { get; set; }
        public Nullable<System.DateTime> RAN_KAPANMA { get; set; }
    
        public virtual CALISMALAR_TBL CALISMALAR_TBL { get; set; }
        public virtual ISTEKLER_TBL ISTEKLER_TBL { get; set; }
        public virtual KULLANICILAR_TBL KULLANICILAR_TBL { get; set; }
        public virtual RENKLER_TBL RENKLER_TBL { get; set; }
    }
}
