//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANDEVULISTERENKLERI_TBL
    {
        public long BR_ID { get; set; }
        public string BR_RENKKODU { get; set; }
        public Nullable<System.TimeSpan> BR_SURE1 { get; set; }
        public Nullable<System.TimeSpan> BR_SURE2 { get; set; }
    }
}
