//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENKLER_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RENKLER_TBL()
        {
            this.RANDEVULAR_TBL = new HashSet<RANDEVULAR_TBL>();
        }
    
        public long RENK_ID { get; set; }
        public string RENK_KOD { get; set; }
        public string RENK_BASLIK { get; set; }
        public string RENK_HEX { get; set; }
        public string RENK_GOSTER { get; set; }
        public Nullable<bool> RENK_AKTIF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RANDEVULAR_TBL> RANDEVULAR_TBL { get; set; }
    }
}
