//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLLER_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROLLER_TBL()
        {
            this.KULLANICILAR_TBL = new HashSet<KULLANICILAR_TBL>();
        }
    
        public long ROL_ID { get; set; }
        public string ROL_ADI { get; set; }
        public short ROL_SIRA { get; set; }
        public string ROL_ACIKLAMA { get; set; }
        public Nullable<bool> ROL_AKTIF { get; set; }
        public string ROL_ANAROL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KULLANICILAR_TBL> KULLANICILAR_TBL { get; set; }
    }
}
