//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSS_TBL
    {
        public long SS_ID { get; set; }
        public Nullable<long> SS_CAL_ID { get; set; }
        public string SS_SORU { get; set; }
        public string SS_CEVAP { get; set; }
        public Nullable<bool> SS_AKTIF { get; set; }
    }
}
