//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class YETKIACIKLAMALAR_TBL
    {
        public long YA_ID { get; set; }
        public string YA_YETKIACIKLAMA { get; set; }
        public string YA_YETKI { get; set; }
    }
}
