//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class YETKILER_TBL
    {
        public long YET_ID { get; set; }
        public Nullable<bool> Y_YONETIM { get; set; }
        public Nullable<bool> Y_GENELAYARLAR { get; set; }
        public Nullable<bool> Y_RANDEVUDURUMLARI { get; set; }
        public Nullable<bool> Y_CIKISKODLARI { get; set; }
        public Nullable<bool> Y_GENELTAKVIM { get; set; }
        public Nullable<bool> Y_CALISMALAR { get; set; }
        public Nullable<bool> Y_CALISMAISLEMLERI { get; set; }
        public Nullable<bool> Y_ROLVEYETKILER { get; set; }
        public Nullable<bool> Y_KULLANICILAR { get; set; }
        public Nullable<bool> Y_KULLANICICALISMALARI { get; set; }
        public Nullable<bool> Y_SSS { get; set; }
        public Nullable<bool> Y_FORUMISLEMLERI { get; set; }
        public Nullable<bool> Y_ISTEKEKLEADMIN { get; set; }
        public Nullable<bool> Y_RANDEVUAKTAR { get; set; }
        public Nullable<bool> Y_RAPOR { get; set; }
        public Nullable<bool> Y_RANDEVULAR { get; set; }
        public Nullable<bool> Y_CAGRILAR { get; set; }
        public Nullable<bool> Y_SESKAYDIBUL { get; set; }
        public Nullable<bool> Y_SESDINLE { get; set; }
        public Nullable<bool> Y_SESDISAAKTAR { get; set; }
        public Nullable<bool> Y_ISTEKLER { get; set; }
        public Nullable<bool> Y_LOGLAR { get; set; }
        public Nullable<bool> Y_KULLANICIIZLE { get; set; }
        public Nullable<bool> Y_OPERATOR { get; set; }
        public Nullable<bool> Y_RANDEVULARIM { get; set; }
        public Nullable<bool> Y_CAGRILARIM { get; set; }
        public Nullable<bool> Y_MESAJLARIM { get; set; }
        public Nullable<bool> Y_FORUMKULLAN { get; set; }
        public Nullable<bool> Y_YARDIM { get; set; }
        public Nullable<bool> Y_ISTEKEKLEOPERATOR { get; set; }
        public Nullable<bool> Y_CAGRIYAP { get; set; }
        public Nullable<bool> Y_BEKLEMEYEAL { get; set; }
        public Nullable<bool> Y_AKTAR { get; set; }
        public Nullable<short> YET_ROLSIRANO { get; set; }
        public Nullable<bool> Y_RANDEVUOLUSTUR { get; set; }
    }
}
